add-main-service
Ksenia91Dumina/java-explore-with-me_2 pull request #2
Opened 2023-03-03 15:07 UTC by Ksenia91Dumina

2023-03-05 12:40 UTC, Ksenia91Dumina commented
Добрый день! Постаралась учесть прошлые замечания. Спасибо!)

2023-03-06 20:08 UTC, sergeymamonov requested changes
Работа выполнена хорошо. Рекомендую сделать более информативное описание вашего проекта в Readme. Это лицо вашего проекта. apiControllers - неверное наименование пакета. Для пакетов используется snake_case.

2023-03-06 20:08 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/addition/MyPageRequest.java
> +public class MyPageRequest extends PageRequest {
В тренировочных проектах наименования типа My... допустимы, но в данной работе лучше отказаться от My...

2023-03-06 20:08 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/addition/MyPageRequest.java
> +        super(from / size, size, sort);
А если пользователь передаст size равно 0, проверяли такой вариант?

2023-03-06 20:08 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/event/model/EventState.java
> +    public static EventState fromString(String text) {
Метод где-то вызывается? И лучше ловить конкретную ошибку, а не просто Exception

2023-03-06 20:08 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        if (event.getState().equals(PUBLISHED)) {
equals нужно вызывать у константного значения. В данном случае PUBLISHED.equals(event.getState()). Это делается потому, что event.getState() может быть равным null, а это приведет к NPE. Указал только одно место, есть еще места, где нужно изменить порядок.

2023-03-06 20:08 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        User initiator = userRepository.findById(userId)
Здесь и в строке 299 можно сразу вернуть результат вычисления выражения без создания промежуточной переменной.

2023-03-06 20:08 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +}
Можно еще добавить обработку на 500 ошибку.

2023-03-06 20:08 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/request/model/RequestState.java
> +        return null;
Можно кинуть ошибку, что переданный статус неизвестен. А то пойдет null в программу и может сделать где-нибудь NPE.

2023-03-06 20:08 UTC, sergeymamonov commented on main-service/src/main/resources/schema.sql
> +    name  VARCHAR(100)                            NOT NULL,
name лучше в кавычки взять, чтобы не спутался с функцией постгреса.

2023-03-07 18:02 UTC, Ksenia91Dumina commented on main-service/src/main/java/ru/practicum/request/model/RequestState.java
> +        return null;
ох... этот тоже не использую уже) убрала вообще метод

2023-03-07 18:03 UTC, Ksenia91Dumina commented on main-service/src/main/resources/schema.sql
> +    name  VARCHAR(100)                            NOT NULL,
Надеюсь здесь правильно поняла

2023-03-07 18:17 UTC, Ksenia91Dumina commented on main-service/src/main/java/ru/practicum/addition/MyPageRequest.java
> +        super(from / size, size, sort);
Добавила аннотации Positive и PositiveOrZero для from и size (как в прошлой работе - в этот раз забыла((( )

2023-03-08 04:05 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        if ((CANCEL_REVIEW.toString()).equals(eventDtoUpdateByUser.getStateAction())) {
Лучше сделать, чтобы getStateAction возвращал перечисление. То есть нарушается ООП, у нас есть объект статус. А здесь метод возвращает статус, но не объектом, а строкой.

2023-03-08 04:07 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        if (!event.getState().equals(PUBLISHED)) {
Лучше по поиску по проекту (Ctrl + Shift + F) поищите equals и проверьте как он вызывается. Нужно, чтобы вызывался от константы или от величины, гарантированно не равно null.

2023-03-08 04:29 UTC, sergeymamonov approved these changes

2023-03-08 11:54 UTC, merged